### ISSUE TITLE
Prompt user to refresh submission list

### ISSUE THREAD

**Issue by matthew-white** [getodk/central-frontend#175]
On the submissions page, users fetch submissions incrementally, in chunks of either 250 or 1,000 submissions. If as part of a new chunk of submissions, we learn that the total count of submissions for the form has changed, we update the count that is shown on the form overview page and the submissions page.

For this issue, we will inform the user more explicitly when the submission count has changed and prompt them to refresh the list. If the count has increased, the prompt should say something like, "*#* new submissions have recently been submitted. Click the **Refresh list** button to view them." If the count has decreased, the prompt should say something like, "*#* submissions have recently been deleted. Click the **Refresh list** button to remove them from the list below."

The "table actions" above the submissions table include the "Refresh list" button. As part of this issue, we might also consider making those actions sticky so that they are visible even as the user scrolls through the submissions list. That work might intersect with #160.

**Comment by clint-tseng** [comment]
It sort of depends on whether/how soon we switch from infinite scroll to something paged. Infinite scroll would suggest sticky actions; otherwise, I feel there is less utility. And because it seems like it would be harder to make both the actions and the table headers stick, as they’re all in separate containers, it seems like not doing it would be ideal if possible.

**Comment by matthew-white** [comment]
Closing after discussing with @lognaturel.
