### ISSUE TITLE
Include Kettle in submission analysis tab

### ISSUE THREAD

**Issue by florianm** [getodk/central-frontend#252]
In the vein of #247 - Kettle looks like a great GUI option to access ODK Central's OData API.

Source: [forum post](https://forum.opendatakit.org/t/automating-data-delivery-using-the-odata-endpoint-in-odk-central/22010) by @schemetrica (David Henry) links to this [tutorial](https://github.com/schemetrica/automating-data-delivery-odk-central).

**Comment by matthew-white** [comment]
I'm working to organize our GitHub issues, and since this issue has been open for a while, I think I'm going to go ahead and close it for now. The team hasn't had a chance to look deeply into using Kettle with ODK Central, although it's an approach that sounds very promising. If we end up landing on a nice Kettle-based workflow and decide that we want to promote that, I think that'd be a good time to return to this issue. If/when we decide on text to promote Kettle, it should be pretty straightforward to add it to the modal.

Thanks, @florianm!

**Comment by florianm** [comment]
For reference, I've mentioned the Kettle tutorial at https://docs.ropensci.org/ruODK/articles/comparison.html

**Comment by schemetrica** [comment]
I'm fine with closing this issue - thanks for keeping me in the loop.

-Dave
