### ISSUE TITLE
text: can we suggest that the encrypted submissions download modal can be closed?

### ISSUE THREAD

**Issue by issa-tseng** [getodk/central-frontend#279]
right now it never says when you can dismiss the modal. we should do that if we can, but maybe there's a reason we can't.

**Comment by lognaturel** [comment]
I don't think this needs to be clever in any way. Something like "If the download has completed, close this" would be enough.

**Comment by matthew-white** [comment]
I took a look at the component, and I think it should be OK for the user to close the modal once the download has completed (and even once it's started). The main thing that's unusual about the modal is that Frontend has limited information about the status of the download; however, the user should still be able to close the modal.

I'm happy to make that text change while I'm localizing that component so that it can get in before the component is translated. How about adding the second sentence below to the message that's shown in the modal?

> Your data download should begin soon. Once it begins, you can close this pop-up. If you have been waiting and it has not started, please try again.

**Comment by issa-tseng** [comment]
s/pop-up/box

otherwise that looks fine to me
