### ISSUE TITLE
Make entity-creation error messages easier to find

### ISSUE THREAD

**Issue by ktuite** [getodk/central-frontend#701]
Backend issue https://github.com/getodk/central-backend/issues/729 describes a scenario on the forum where there is a "Problem creating Entity" message with no explanation. The message is in the audit log JSON, but weirdly not showing up.

One fix should be made:
1. Double-check that the error message is getting extracted from the audit log details in the right way, especially for this situation

This other idea has been moved to the parking lot
- Add "entity.create.error" as an option in the audit log filter menu.

**Comment by matthew-white** [comment]
> Add "entity.create.error" as an option in the audit log filter menu.

Since we don't don't show `entity.create` or `submission.create` events in the main server audit log, my instinct is that we also shouldn't show `entity.create.error` events. Then again, maybe we can expect that there won't be many `entity.create.error` events, so including that action wouldn't dramatically increase the size of the audit log.

Whether or not we include `entity.create.error` in the main audit log, I do think it'd be nice to surface those three actions in Frontend somewhere. Maybe in a project-specific audit log?

**Comment by ktuite** [comment]
That's true. I'm willing to wait for a project (or even dataset) -specific audit log!

**Comment by ktuite** [comment]
But I did make a small PR to address the first part - of showing entity create error messages when they're not in the main error message location.

**Comment by matthew-white** [comment]
> I'm willing to wait for a project (or even dataset) -specific audit log!

Ooh a dataset-specific audit log, that sounds helpful!

I just merged #717. 🚀 What do you think about closing this particular issue? And possibly filing a new issue about the idea of another audit log to surface `entity.create.error` and other events? (Or it could be noted in the parking lot.)

**Comment by ktuite** [comment]
Note to QA: 
We're fixing the backend issue behind this error so it won't be possible to fresh errors of this case appear, but here is a link to a [submission](https://test.getodk.cloud/#/projects/422/forms/trees_registration_demo/submissions/uuid%3A8fbd68c9-974a-44b4-8248-4145dd635c26) from an earlier version that has an entity error and should show the error message.

**Comment by srujner** [comment]
**Tested with Success!**

**Comment by dbemke** [comment]
Tested with Success!
