### ISSUE TITLE
small screens: menu stays open after logout

### ISSUE THREAD

**Issue by alxndrsn** [getodk/central-frontend#828]
On slim screens, the top-level menu stays open after logout:

### Expected

Menu should close completely.

#### Before

User-specific sub-menu is open.

#### After

![Screenshot_2023-07-19_17-33-25](https://github.com/getodk/central-frontend/assets/191496/673a1c4d-186d-42d7-9d47-01ce5ce6cc9b)

**Comment by matthew-white** [comment]
At the moment, we're not prioritizing issues with mobile (of which there are quite a few!). I'm thinking of implementing #785 at some point soon, which won't make for a delightful experience on mobile, but at least would be more usable. If we implemented #785, then I think the issue here wouldn't come up.

I think we should close this issue for now, but we could reopen if/when we start prioritizing mobile.
